### ISSUE TITLE
Extend tailwind with the required colors and fonts

### ISSUE THREAD

**Issue by wisammechano** [Iraq-RBC-Capstones-2021/capstone-react-jobie#3]
accent: #EC7063
dark: #34495E
light: #E7ECF2
primary: #072451
secondary: #154360

These are extracted from the Figma file. You would stick to these colors only plus gray-200 for highlighting, and white when necessary.

Also, please make sure to onboard your peers on how to use these when they work on their components.

**Comment by wisammechano** [comment]
@rebaz36 , you can also assign to aya once she joins

**Comment by rebaz36** [comment]
@ayasalam0 This is your current task
